# Generated by Django 6.0.1 on 2026-01-29 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                (
                    "typ",
                    models.CharField(
                        choices=[("stale", "Stałe"), ("zmienne", "Zmienne")],
                        default="zmienne",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kategorie",
            },
        ),
        migrations.CreateModel(
            name="Oszczednosci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                (
                    "kwota_docelowa",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("opis", models.TextField(blank=True, null=True)),
                (
                    "uzytkownik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Osoba",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Oszczędności",
            },
        ),
        migrations.CreateModel(
            name="Wydatek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200)),
                ("kwota", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "data_wydatku",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("opis", models.TextField(blank=True, null=True)),
                (
                    "kategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_app.kategoria",
                    ),
                ),
                (
                    "uzytkownik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Osoba",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wydatki",
            },
        ),
    ]
