# Generated by Django 6.0.1 on 2026-01-29 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Przychod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=100, verbose_name="Źródło przychodu"),
                ),
                (
                    "kwota",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Kwota"
                    ),
                ),
                ("data_przychodu", models.DateField(auto_now_add=True)),
                (
                    "uzytkownik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Osoba",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Przychody",
            },
        ),
    ]
