# Generated by Django 6.0.1 on 2026-01-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_app", "0002_przychod"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotatkaMiesiaca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tresc", models.TextField(verbose_name="Treść notatki")),
                ("data_aktualizacji", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Notatki miesiąca",
            },
        ),
    ]
