# Generated by Django 6.0.1 on 2026-01-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_app", "0003_notatkamiesiaca"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotatkaMiesiaca",
        ),
        migrations.AlterField(
            model_name="kategoria",
            name="typ",
            field=models.CharField(
                choices=[("staly", "Wydatek stały"), ("zmienny", "Wydatek zmienny")],
                default="zmienny",
                max_length=10,
            ),
        ),
    ]
