# Generated by Django 6.0.1 on 2026-01-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_app", "0004_delete_notatkamiesiaca_alter_kategoria_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="wydatek",
            name="notatki",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
